version: '3.8'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../workspaces:/workspaces
    command: /bin/sh -c "while sleep 1000; do :; done"  
    network_mode: host
    